---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.bie
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    config:
        locations:
            - file:///data/ala-bie/config/ala-bie-config.properties
            - file:///data/ala-bie/config/ala-bie-config.yml
            - file:///data/ala-bie/config/ala-bie-config.groovy
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
#Required so that the gbif-ecat library does not bugger up initialisation from its internal application.properties
app:
  name: ala-bie
  dataDir: /tmp/gbif-ecat
skin:
  layout: ala
  orgNameLong: Atlas of Living Australia
  orgNameShort: ALA
  fluidLayout: false
bie:
  baseURL: http://localhost:8080
  searchPath: /search
  index:
    url: http://localhost:8090/bie-index
facets: idxtype,rank,speciesGroup,locatedInHubCountry,imageAvailable,conservationStatusAUS_s,conservationStatusACT_s,conservationStatusNSW_s,conservationStatusQLD_s,conservationStatusVIC_s,conservationStatusTAS_s,conservationStatusSA_s,conservationStatusWA_s,conservationStatusNT_s
speciesParent: https://lists.ala.org.au/iconic-species
serverName: http://dev.ala.org.au:8080
projectNameShort: Atlas
projectName: Atlas of Living Australia
biocache:
    baseURL: "http://biocache.ala.org.au"
biocacheService:
    baseURL: http://biocache.ala.org.au/ws
    queryContext:
spatial:
    baseURL: http://spatial.ala.org.au
layersService:
    baseURL: http://spatial.ala.org.au/ws
ala:
    baseURL: http://www.ala.org.au
collectory:
    baseURL: http://collections.ala.org.au
    threatenedSpeciesCodesUrl: http://collections.ala.org.au/public/showDataResource
regions:
    baseURL: http://regions.ala.org.au
bhl:
    baseURL: http://bhlidx.ala.org.au
speciesList:
    baseURL: http://lists.ala.org.au
alerts:
    baseUrl: http://alerts.ala.org.au/ws/
sightings:
    guidUrl: http://sightings.ala.org.au/
eol:
    lang: en
defaultDecimalLatitude: -25.61
defaultDecimalLongitude: 134.35
defaultZoomLevel: 4
image:
    thumbnailUrl: http://images.ala.org.au/image/proxyImageThumbnail?imageId=
map:
    default:
        id:
        token:
        url: http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png
        attr: Map data &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='http://cartodb.com/attributions'>CartoDB</a>
        domain: abcd
        colour: e6704c
    simpleMapButton: false
bieService:
  queryContext:
googleMapsApiKey: AIzaSyB0HIkSCV2EdkG50uM7s96IEbO6wUHTqy0
languageCodesUrl: /languages.json
geocode.querySuffix:
occurrenceCounts:
    enabled: true
additionalResultsFields: kingdom
admin_role: ROLE_ADMIN
allowedImageEditingRoles: ROLE_ADMIN
additionalMapFilter:
synonymsTypes: synonym